[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-10
upload_speed = 115200
upload_resetmethod = nodemcu
lib_deps =
    adafruit/Adafruit GFX Library@^1.11.0
    mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^3.0.0
